
export const sideData = {
  coverIcon: '',
  avatar: '',
  title:'NFL Canada',
  subTitle:'Canada',
  post:'7 Mill',
  follower:'17456',
  followings:'316',
  link:'https://canada.nfl.com',
  description:'This is descripton for this. This is descripton for this. This is descripton for this. This is descripton for this. This is descripton for this.',
}

export const playerData = [
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  },
  {
    coverIcon: '',
    avatar: '',
    Name:'NFL Canada',
    league:'Canada',
    leagueFlag:'7 Mill',
    position:'Cb',
    subtitle:'Football',
  }
]