export const GET_CLUB_DATA_REQUEST = 'GET_CLUB_DATA_REQUEST'; 
export const GET_CLUB_DATA_SUCCESS = 'GET_CLUB_DATA_SUCCESS'; 
export const GET_CLUB_DATA_ERROR = 'GET_CLUB_DATA_ERROR'; 

export const GET_PLAYER_LIST_REQUEST = 'GET_PLAYER_LIST_REQUEST'; 
export const GET_PLAYER_LIST_SUCCESS = 'GET_PLAYER_LIST_SUCCESS'; 
export const GET_PLAYER_LIST_ERROR = 'GET_PLAYER_LIST_ERROR'; 